// Integration fixtures are the untouched distribution ZIPs, passed on the command line.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const Zip = require('adm-zip')
const { patchEntries, prepareShaderPack } = require('../app/assets/js/cosmeticshadercompat')
const [low, high] = process.argv.slice(2)
assert(low && high, 'Usage: node test/cosmeticshadercompat.cjs LOW_ORIGINAL.zip HIGH_ORIGINAL.zip')
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'barkan-cosmetic-shaders-'))
const report = []
try {
    fs.mkdirSync(path.join(tmp, 'shaderpacks'))
    for (const [quality, source, expected] of [['low', low, 5], ['high', high, 15]]) {
        const zip = new Zip(source)
        const before = new Map(zip.getEntries().filter(e => !e.isDirectory).map(e => [e.entryName, e.getData()]))
        const fixed = patchEntries(before)
        assert.equal(fixed.changed.length, expected)
        for (const [name, data] of before) if (!fixed.changed.includes(name)) assert.deepEqual(fixed.entries.get(name), data, name)
        assert.equal(patchEntries(fixed.entries).changed.length, 0)
        const partial = new Map(fixed.entries)
        partial.set(fixed.changed[0], before.get(fixed.changed[0]))
        assert.throws(() => patchEntries(partial), /Partial/)
        const fileName = `barkan-shaders-${quality}.zip`
        const raw = path.join(tmp, 'shaderpacks', fileName)
        fs.copyFileSync(source, raw)
        fs.writeFileSync(raw + '.txt', 'USER_TUNING=true\n')
        const original = fs.readFileSync(raw)
        const derived = path.join(tmp, 'shaderpacks', prepareShaderPack(tmp, fileName))
        assert.deepEqual(fs.readFileSync(raw), original, 'downloaded original changed')
        assert.equal(fs.readFileSync(derived + '.txt', 'utf8'), 'USER_TUNING=true\n')
        const stat = fs.statSync(derived).mtimeMs
        prepareShaderPack(tmp, fileName)
        assert.equal(fs.statSync(derived).mtimeMs, stat, 'warm start rewrote pack')
        fs.writeFileSync(derived, 'corrupt')
        prepareShaderPack(tmp, fileName)
        assert(new Zip(derived).getEntries().length > 0, 'did not repair corrupt derivative')
        fs.writeFileSync(derived + '.txt', 'USER_TUNING=changed\n')
        zip.addFile('barkan-test-download-revision.txt', Buffer.from('new source'))
        zip.writeZip(raw)
        prepareShaderPack(tmp, fileName)
        assert.equal(new Zip(derived).readAsText('barkan-test-download-revision.txt'), 'new source')
        assert.equal(fs.readFileSync(derived + '.txt', 'utf8'), 'USER_TUNING=changed\n')
        report.push({quality, changedFiles:expected, preservedEntries:before.size - expected, rawPreserved:true, idempotent:true, cached:true, repaired:true, updateRebuilt:true, tuningPreserved:true})
    }
    assert.throws(() => patchEntries(new Map()), /Unknown shader layout/)
    assert.throws(() => prepareShaderPack(tmp, '../escape.zip'), /Invalid shader/)
    console.log(JSON.stringify(report, null, 2))
} finally { fs.rmSync(tmp, {recursive:true, force:true}) }
